### PR TITLE
Typed

### PR DESCRIPTION
**Pull request by pnearing**
I typed all the functions in the classes.

### CODE REVIEW

**Comment by N4S4** [comment]
This was a huge job and thank you very much for it.
What do you think if you PR me this in a new branch? For two reason
First I don't have much time I would feel shame to not continue this best practice
Second I don't want to spoil this great job

Making the new branch I can see if I can keep It up and eventually merge it

Is it ok for you?

**Comment by N4S4** [comment]
you know diving into typing now I regret not merging this straight into master branch

**Comment by pnearing** [comment]
Thank you very much, I'm glad I could help. I was thinking about working on exceptions for the api, such as requests.raise_for_status. What do you think?

**Comment by N4S4** [comment]
I think it would be good!

**Pull request merged**
