### PR TITLE
Improving code

### PR DESCRIPTION
**Pull request by fipwmaqzufheoxq92ebc**
Hi,
this PR fixes some problems in the Improving-Code-Branch:

- sys_info and virtualization import "auth", but this module doesn't exist. I removed their import from __init__.py, otherwise you can't "import synology_api". 
I will try to rewrite them in the new Code-Style and add an additional PR.

- All parameters, except 'api_name' and 'api_method', were ignored by "wrap_api_method".
Because of that, every function which has required parameters, failed with error:400

- The Audio-station used the "@Synology.api_call" decorator (which doesn't exist). I replaced them with "@api_call()"

- Sometimes "@api_call" and "@api_call()" were used. Because only "@api_call()" works, I replaced all occurrences of "@api_call"

- The login()-Factory-Function can't use instance attributes/properties (e.g. "app"), so I set the app-name as class attribute.

Some issues I also noticed:
- The request path of the Auth-API is constant, but as far I understand the API, you should get it from a call to "SYNO.API.Info" (Working example of FileStation API, Page 10, Step 1/2)
- Why does the "Synology.login()" method add the session-data and url as class attributes? (Why not as instance attributes?)
- For the AudioStation, __init__ gets the Connection-Parameters, while DownloadStation and FileStation use Synology.login as factory-method. I'm not sure which approach is better, so I didn't change that. (The AudioStation-Class doesn't work currently.)

### CODE REVIEW

**Comment by N4S4** [comment]
HI,
yes I know it is a bit messy for now, Audiostation and sys_info were not adapted to this branch yet so that is why it looks still like that, it is still in a primordial status and time is not on my side, all modules should based on synology module so as filestation and downloadstation modules are.
Thank you for the time spent on it, have you tested your upgrade yet? I will test it as soon i have a bit of time.

regarding the issues that you found:

- Yes that is the correct way to find the API info, auth.py is deprecated in this branch as synology.py took over job should be done by "populate_api_dict", at least that should be the plan.

- @v7x can probably answer this in more detailed way, in case is good to test in both ways

- Audiostation is not updated yes as well as sys_info and virtualization so filestation and download station are the example to follow, Synology.login() is the one to use

**Comment by fipwmaqzufheoxq92ebc** [comment]
I did some testing (but not much) on the functions, which I changed more than just the decorator (e.g. login, wrap_api_method), and some of the other functions.

**Comment by N4S4** [comment]
ok I will let you know, as soon i have spare time I'll test your branch

**Comment by N4S4** [comment]
so, as far as I tested, login and logout are working fine, I don't understand why is getting different SID when logging in in different modules, which it shouldn't, I will test further more and see why.
many functions are working correctly as well the decorator so great job! 
I will merge it soon but before doing that I want to see if i can work on it better.
thank you for your support I hope you will continue!

**Comment by fipwmaqzufheoxq92ebc** [comment]
Hi,
I rewrote the Virtualization-, SysInfo- and AudioStation- Modules.

I don't use Virtualization and AudioStation, so I didn't test them. For SysInfo, I chose randomly some functions and tested them.

The SID is currently not reused between the modules. For each login()-call you get a new SID. 
I'm not sure if we should reuse it, as we need to prevent that e.g. a logout() of DownloadStation would also logout the FileStation. 
(Another possibility would be to count how many Modules use this SID, and logout if the last Module uses logout() )

**Comment by N4S4** [comment]
I finally had time to do some testing.
Yes I confirm is working good, I'm glad you made it work it seems quite responsive too!

Yes you are right to not use the same SID for all modules, I did not think about the logout part.
We can work on a count implementation but the best it to refine the entire module first.

you did a great job and i count on your support in the future!

**Pull request merged**
