### PR TITLE
Add Cloud Sync implementation

### PR DESCRIPTION
**Pull request by joeperpetua**
Adding implementation for Cloud Sync API, there are around 20 functions fully documented.

I was experimenting a big with the docstrings and I think it could be the standard documentation for the project (as we discussed once in TG), what do you think about that?

### CODE REVIEW

**Comment by joeperpetua** [comment]
You can use this template for testing the functions :) 
```python
def json_pp(dict):
    return json.dumps(dict, indent=4, sort_keys=True)
    
def test_cloudsync(self):
    cs = CloudSync(
            ip_address=self.config["synology_ip"], 
            port=self.config["synology_port"],
            username=self.config["synology_user"],
            password=self.config["synology_password"],
            secure=bool(self.config["synology_secure"]), 
            cert_verify=False,
            dsm_version=int(self.config["dsm_version"]), 
            debug=True,
            otp_code=self.config["otp_code"]
    )

    self.assertIsNotNone(cs)
    self.assertIsNotNone(cs.session)

    def test_api(result, method):
        print(f'====== Testing {method} ======')
        print(f'== Type of response: {type(result)}')
        print(f'== Response:\n {json_pp(result)}')
    
    test_api(cs.get_pkg_config(), 'get_pkg_config')
    test_api(cs.get_connections(), 'get_connections')
    test_api(cs.get_connection_settings(conn_id=3), 'get_connection_settings')
    test_api(cs.get_connection_information(conn_id=3), 'get_connection_information')
    test_api(cs.get_connection_auth(conn_id=3), 'get_connection_auth')
    test_api(cs.get_connection_logs(conn_id=3, keyword='OCR', log_level=2, action=1, date_from=1724418110, date_to=1724435779), 'get_connection_logs')
    test_api(cs.get_tasks(conn_id=3), 'get_tasks')
    test_api(cs.get_task_filters(sess_id=4), 'get_task_filters')
    test_api(cs.get_task_cloud_folders(sess_id=4, remote_folder_id='xxxxxxxx'), 'get_task_cloud_folders')
    test_api(cs.get_recently_modified(), 'get_recently_modified')
    test_api(cs.set_pkg_config(pkg_volume='/volume2', log_count=20000, workers=5, admin_mode=True), 'set_pkg_config')
    test_api(cs.set_relink_behavior(delete_from_cloud=False), 'set_relink_behavior')
    test_api(cs.set_connection_settings(conn_id='3', task_name="Cute task", pull_event_period=60, max_upload_speed=1024*1024, max_download_speed=1024*1024, part_size=128), 'set_connection_settings')
    days = [
        '111111111111111111111111', # sunday    - hours from 0 to 23
        '111111111111111111111111', # monday    - hours from 0 to 23
        '111111111111111111111111', # tuesday   - hours from 0 to 23
        '111111111111111111111111', # wednesday - hours from 0 to 23
        '111111111111111111111111', # thursday  - hours from 0 to 23
        '111111111111111111111111', # friday    - hours from 0 to 23
        '100000000000000000000000', # saturday  - hours from 0 to 23
    ]
    test_api(cs.set_connection_schedule(conn_id=3, enable=True, schedule_info=days), 'set_connection_schedule')
    test_api(cs.set_task_settings(sess_id=4, sync_direction="ONLY_DOWNLOAD", consistency_check=True), 'set_task_settings')
    test_api(cs.set_task_filters(sess_id=4, filtered_paths=["/test1"], filtered_filenames=["this is a file name"], filtered_extensions=["mp3", "uwu", "png"], max_upload_size=1024*1024), 'set_task_filters')
    test_api(cs.connection_pause(conn_id=3), 'connection_pause')
    test_api(cs.connection_resume(conn_id=3), 'connection_resume')
    test_api(cs.connection_remove(conn_id=2), 'connection_remove')
    test_api(cs.task_remove(conn_id=3, sess_id=5), 'task_remove')
    ```

**Comment by N4S4** [comment]
I think Docstring are the best way to document, you are right. Not sure why apart from cloud_sync and readme  file, other files seems have been changed fully so i cannot see differences from before, I will have a test of the code. Thank you for your work btw!!

**Comment by N4S4** [comment]
Yeah no problem i was wondering just what changed in  auth file but ill check it out

**Comment by joeperpetua** [comment]
In auth.py should be only importing the CloudSyncException class and then in 321/322 adding the case to the if/else.

**Comment by whoishina** [comment]
Thank you for creating this package, however, I couldn't find any method for adding a new task to a connection. Could you explain why?

From what I've gathered while using the web interface, to add a task to the task list in a connection, there is an API: SYNO.CloudSync with the method create_session. I tried writing a method inheriting from the CloudSync class to implement create_session, but I encountered an error message: Data request failed: Error 120 - Preserve for other purpose. It seems like these are two different types of APIs?

image

**Comment by joeperpetua** [comment]
It was originally in the plan to add the method to create a task, but due to the amount of public clouds there are and the request complexity I decided to drop it.

The errors from the Web API are not very useful, you can check in `/var/log/synoscgi.log` to get more descriptive error messages (most of the time).

**Comment by whoishina** [comment]
@joeperpetua Thank you for your response. I will try reading the log from Synology and checking as per your instructions. If successful, I hope to contribute a part to your project. Could you provide some more information about creating tasks? (if you have any)

**Comment by joeperpetua** [comment]
No worries, I will check my notes when i get back home later today and see what i can find. 

PD: the author is @N4S4 , I just made the impenetrable for Cloud Sync in this case 😉

**Comment by whoishina** [comment]
i've checked the log `/var/log/synoscgi.log` file and only 'useful' message is 'invalid parameter' :cry: 

image

**Comment by whoishina** [comment]
@joeperpetua I have just reviewed your source code and Synology's, and I was finally able to add the feature of creating a new task list into the Cloud Sync connection. I will create a pull request to add this feature for the community

**Comment by whoishina** [comment]
@N4S4 @joeperpetua Many thanks, awesome repository!!!

**Comment by joeperpetua** [comment]
Nice one! Sorry I didn't come back earlier, pretty busy week 😅

**Pull request merged**
