### PR TITLE
Add FileStation.Download method for open and download mode

### PR DESCRIPTION
**Pull request by kidburglar**
It add the download method for the open/download mode.

For the open mode I use sys because print provoke a broken pipe.
With this code I can use `python code.py | mpv -`

For the download mode I thought it would be better to save it with the chunk method instead to load it completely before saving it.

Feel free to change some code part if needed so that it match the rest of the code.

Cheers.

### CODE REVIEW

**Comment by kidburglar** [comment]
I same think the for https://github.com/N4S4/synology-api/pull/5/files#diff-f3bad907cf1eb0cbb9052e399a6fc1deR992 may be removed. I take the upload_file code as inspiration

**Comment by N4S4** [comment]
would you check if the modification I've made is working for you?
I had minor issues with parse and _sid

thanks

**Comment by kidburglar** [comment]
Hello, I just tested it again and it look like the " ' " for the sid is making it fail for me.

If I remove them again, it work.
I use python3 on Debian 10 if it can maybe help to find what it's wrong.

**Comment by N4S4** [comment]
Hi, 
what kind of error is giving you? 

I tested on windows python 3.7 and was giving 404 error
but on ubuntu 18 is working with and without, it could be my station issue so maybe better to remove them and I will make few more tests later on! 
For now I will merge the request removing the " ' "

**Comment by kidburglar** [comment]
Hello, in my case it was an 119 error if I remember, like the "sid" was not correctly recognize.

I not have windows so it's little difficult for me to test, but I find that weird to have `import urllib` and  `from urllib import parse` maybe we could try to only use the second one and see if it work.

For what I see with `from urllib import parse` I can use `parse.quote_plus(...)` on Linux, maybe it could work properly on windows also.

**Comment by N4S4** [comment]
yes I confirm it is working on windows just with `from urllib import parse` so better to keep using this, as well now I tested all again seems to work without errors so it was something wrong with mine

**Comment by N4S4** [comment]
Hello,
Sorry I did not see that you changed the file before I committed mine

**Pull request merged**
