### PR TITLE
Add https endpoint support

### PR DESCRIPTION
**Pull request by Egor-S**
Build _base_url with `https` or `http` (default) schema

### CODE REVIEW

**Comment by tduboys** [comment]
Instead of adding another parameter, is it not better to pass directly the base url ?
And use a second constructor that builds this URL from IP/PORT combo for compatibility reasons.
cf #20

**Comment by N4S4** [comment]
help me to understand the #20  was not implemented in this one? which one is the most recent?

**Comment by Egor-S** [comment]
I think you should close my PR, because it adds only one case for base_url (https support, no reverse-proxy).

**Comment by N4S4** [comment]
ok i just close this #23 was close automatically after the merge.
I'll wait for ur final PR

**Pull request closed without merging**
