### PR TITLE
 Update filestation.upload with Syno API. 

### PR DESCRIPTION
**Pull request by karoldob**
Verified with DSM 6.2.2

### CODE REVIEW

**Comment by karoldob** [comment]
Hi, It was problem, because API not worked for me before.
Today I'll make small improvement - ability to set destination filename (different from source).

**Comment by karoldob** [comment]
I deleted source branch because there was too much my private details. I would appreciate if you will delete this pull-request completely. 
And next you can pull changes from my forked repo - there are the same fixes with corrected git history :)

**Comment by N4S4** [comment]
👍 ok no pb

**Comment by N4S4** [comment]
correct me if I'm wrong, I think you should delete the entire branch.
I read this https://help.github.com/en/articles/deleting-and-restoring-branches-in-a-pull-request
but I don't have this option, let me know if you can otherwise I'll see what i can do

**Comment by karoldob** [comment]
The story on my side:
1. I created fork of your repo, made feral commit. created pull request to your repo. 
2. Then I realized that my commit has to much my detalis, so I deleted branch and entire fork of your repo.
3. Created new repo(fork) and commit changes in new correct way. 
4. This is why this pull request has comment "...wants to merge... from unknown repository"

I hoped it could be possible to delete only closed pull request, as suggested here:
https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github
But still not sure. I you will find something, it will be great :)

**Comment by N4S4** [comment]
Oh ok I see, I don't see any info maybe deleting your fork you did the job
But if you feel unsafe I will ask github and see what they can do

**Comment by N4S4** [comment]
ok I wrote to the support let's see what they say

**Pull request closed without merging**
